### ISSUE TITLE
When will version 0.3.4 be released?

### ISSUE THREAD

**Issue by noellemorris** [TapWithUs/tap-android-sdk#13]
Hi,
I'm using the tap sdk in an Android library (aar) and I would like to know when the changes reflected in the master branch ("0.3.4") will be released. Thanks!

**Comment by KibiH** [comment]
Hi there

Since bintray/jcenter is no longer functional, we have moved to do our SDK hosting on mavenCentral which is the new most popular hosting site
I have just released version 0.3.5 to mavenCentral, this includes all the latest changes and Javadocs.

Please note the changes in the ReadMe to explain how to set up your dependency

Hope that helps!
